### ISSUE TITLE
Back One Page Button Broke

### ISSUE THREAD

**Issue by jsaylor525** [containers-everywhere/contain-google#40] opened 2019-01-24 20:10 UTC
When the extension is enabled the back one-page button doesn't function properly.

**Comment by Perflyst** [comment] 2019-02-03 17:35
Duplicate of #16 
Please use "middle mouse click" to open a link in a new tab.

**Closed** 2019-02-03 17:35 UTC
Labels: duplicate

**Comment by kriki200** [comment] 2019-08-22 23:47
Same here cant go back to google's tab...
